default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: varejo_dev
  username: postgres
  password: postgres

test:
  <<: *default
  database: varejo_test

production:
  <<: *default
  database: varejo
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
